export type Email = {
	id: number
	folder: string
	from: string
	to: string
	subject: string
	preview: string
	time: string
	date: string
	unread: boolean
	starred: boolean
	encrypted: boolean
	body: string
	quote?: string
	after?: string
}

export type Folder = {
	id: string
	label: string
	icon: string
	count?: number
}

export const folders: Folder[] = [
	{
		id: "inbox",
		label: "inbox",
		icon: "M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75",
		count: 3,
	},
	{
		id: "sent",
		label: "sent",
		icon: "M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5",
	},
	{
		id: "drafts",
		label: "drafts",
		icon: "M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125",
		count: 1,
	},
	{
		id: "starred",
		label: "starred",
		icon: "M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.562.562 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.562.562 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z",
	},
	{
		id: "snoozed",
		label: "snoozed",
		icon: "M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z",
	},
	{
		id: "trash",
		label: "trash",
		icon: "M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0",
	},
]

export const emails: Email[] = [
	{
		id: 1,
		folder: "inbox",
		from: "bob@h.xyz",
		to: "hi@h.xyz",
		subject: "ethdenver plans",
		preview: "are you coming next week? we just shipped the new batch auction engine...",
		time: "11:42 am",
		date: "feb 7, 2026",
		unread: true,
		starred: false,
		encrypted: true,
		quote:
			"can you review the surplus distribution model and confirm what should ship in v2 vs v3?",
		body: "hey,\n\nare you coming to ethdenver next week? we just shipped the new batch auction engine — 40% better surplus capture across the board.\n\nwant to walk you through the numbers over dinner wednesday. also need your input on something:",
		after:
			"the discussion is in the #protocol channel. would be good to align before the talk on thursday.\n\nlet me know.\n\n— bob",
	},
	{
		id: 2,
		folder: "inbox",
		from: "Ethereum Foundation",
		to: "hi@h.xyz",
		subject: "security advisory: client update v4.2.2",
		preview: "we've identified a potential vulnerability in the latest consensus client update...",
		time: "9:15 am",
		date: "feb 7, 2026",
		unread: true,
		starred: false,
		encrypted: true,
		body: "hi,\n\nwe've identified a potential vulnerability in the latest consensus client update (v4.2.1). all validator operators should update to v4.2.2 immediately.\n\nthis patch addresses a critical edge case in block attestation that could lead to incorrect finality under specific network conditions.\n\nplease update your nodes at your earliest convenience.\n\n— ethereum foundation security team",
	},
	{
		id: 3,
		folder: "inbox",
		from: "alice.eth",
		to: "hi@h.xyz",
		subject: "gm",
		preview: "sent you 0.1 ETH for the coffee yesterday. see you at ethdenver?",
		time: "yesterday",
		date: "feb 6, 2026",
		unread: true,
		starred: true,
		encrypted: true,
		body: "hey!\n\njust sent you 0.1 ETH for the coffee yesterday. see you at ethdenver next week? heard the keynote lineup is insane this year.\n\n— alice",
	},
	{
		id: 4,
		folder: "inbox",
		from: "Uniswap",
		to: "hi@h.xyz",
		subject: "governance: proposal UNI-247",
		preview: "a new governance proposal has been submitted. vote on fee tier adjustments...",
		time: "yesterday",
		date: "feb 6, 2026",
		unread: false,
		starred: false,
		encrypted: false,
		body: "a new governance proposal has been submitted to the uniswap dao.\n\nproposal UNI-247: fee tier adjustments for v4 concentrated liquidity pools. the proposal suggests reducing the default fee from 0.3% to 0.25% for major pairs.\n\nvoting ends feb 14, 2026.\n\nview proposal and cast your vote on governance.uniswap.org",
	},
	{
		id: 5,
		folder: "inbox",
		from: "h.xyz",
		to: "hi@h.xyz",
		subject: "welcome to h.xyz",
		preview: "your email address is now active. all messages are end-to-end encrypted.",
		time: "feb 5",
		date: "feb 5, 2026",
		unread: false,
		starred: false,
		encrypted: true,
		body: "welcome to h.xyz!\n\nyour email address hi@h.xyz is now active.\n\n— end-to-end encrypted by default\n— no personal data stored\n— connected to your wallet\n\nyou can start sending and receiving messages immediately.",
	},
	{
		id: 6,
		folder: "inbox",
		from: "OpenSea",
		to: "hi@h.xyz",
		subject: "new offer on your collection",
		preview: "someone made an offer of 2.4 ETH on item #0042 in your collection...",
		time: "feb 4",
		date: "feb 4, 2026",
		unread: false,
		starred: false,
		encrypted: false,
		body: "you received a new offer.\n\ncollection: genesis artifacts\nitem: #0042\noffer: 2.4 ETH ($6,834.31)\nfrom: 0x7a2e...f391\nexpires: feb 10, 2026\n\nview and accept on opensea.io",
	},
	{
		id: 7,
		folder: "sent",
		from: "hi@h.xyz",
		to: "alice.eth",
		subject: "re: gm",
		preview: "yes! landing wednesday afternoon. let's grab dinner at that ramen place...",
		time: "11:30 am",
		date: "feb 7, 2026",
		unread: false,
		starred: false,
		encrypted: true,
		body: "yes! landing wednesday afternoon. let's grab dinner at that ramen place near the convention center.\n\nalso — thanks for the ETH, didn't have to do that.\n\nsee you there.",
	},
	{
		id: 8,
		folder: "sent",
		from: "hi@h.xyz",
		to: "bob@h.xyz",
		subject: "re: ethdenver plans",
		preview: "definitely coming. dinner wednesday works. i'll review the surplus model...",
		time: "10:05 am",
		date: "feb 7, 2026",
		unread: false,
		starred: false,
		encrypted: true,
		body: "definitely coming. dinner wednesday works.\n\ni'll review the surplus model tonight and send thoughts before we meet. leaning toward pushing the rebate mechanism to v3.\n\nsee you there.",
	},
	{
		id: 9,
		folder: "sent",
		from: "hi@h.xyz",
		to: "0x7a2e...f391",
		subject: "counter offer: #0042",
		preview: "appreciate the offer but looking for at least 3.2 ETH on this piece...",
		time: "feb 5",
		date: "feb 5, 2026",
		unread: false,
		starred: false,
		encrypted: true,
		body: "appreciate the offer but looking for at least 3.2 ETH on this piece. it's one of the first 50 minted and has provenance from the original drop.\n\nlet me know if you'd like to counter.",
	},
	{
		id: 10,
		folder: "drafts",
		from: "hi@h.xyz",
		to: "vitalik.eth",
		subject: "re: account abstraction feedback",
		preview: "thanks for the thoughts on guardian rotation. i've been thinking about...",
		time: "feb 6",
		date: "feb 6, 2026",
		unread: false,
		starred: false,
		encrypted: true,
		body: "thanks for the thoughts on guardian rotation. i've been thinking about a hybrid approach:\n\n— 30 day timeout for 2-of-3 guardian failure\n— social recovery fallback via ENS attestation\n— optional dead man's switch for extended inactivity\n\nstill refining the tradeoffs. will have a more complete writeup by",
	},
	{
		id: 11,
		folder: "starred",
		from: "bob@h.xyz",
		to: "hi@h.xyz",
		subject: "surplus model v2 spec",
		preview: "here's the full spec for the surplus distribution model. key changes from v1...",
		time: "jan 31",
		date: "jan 31, 2026",
		unread: false,
		starred: true,
		encrypted: true,
		body: "here's the full spec for the surplus distribution model.\n\nkey changes from v1:\n— proportional distribution instead of flat\n— 72h settlement window\n— retroactive rebates for high-volume traders\n\ni've attached the simulation results. the new model captures 40% more surplus while keeping gas costs flat.\n\nlet me know what you think.\n\n— bob",
	},
	{
		id: 12,
		folder: "starred",
		from: "vitalik.eth",
		to: "hi@h.xyz",
		subject: "re: account abstraction feedback",
		preview: "thanks for the writeup. the approach to social recovery is solid but...",
		time: "jan 29",
		date: "jan 29, 2026",
		unread: false,
		starred: true,
		encrypted: true,
		body: "thanks for the writeup. i think the approach to social recovery is solid but the guardian rotation mechanism needs more thought.\n\nspecifically: what happens if 2 of 3 guardians go offline permanently? the timeout-based fallback you proposed could work but 90 days feels too long.\n\nwould love to discuss more at ethdenver if you're around.",
	},
	{
		id: 13,
		folder: "snoozed",
		from: "Aave",
		to: "hi@h.xyz",
		subject: "governance: risk parameter update",
		preview: "the aave risk council has proposed changes to the collateral factors...",
		time: "feb 4",
		date: "feb 4, 2026",
		unread: false,
		starred: false,
		encrypted: false,
		body: "the aave risk council has proposed changes to the collateral factors for wstETH and rETH on ethereum mainnet.\n\nproposed changes:\n— wstETH LTV: 75% to 78%\n— rETH LTV: 72% to 75%\n\nvoting opens feb 8, 2026.\n\nreview the full proposal on governance.aave.com",
	},
	{
		id: 14,
		folder: "snoozed",
		from: "ENS",
		to: "hi@h.xyz",
		subject: "domain renewal: h.eth",
		preview: "your ENS domain h.eth expires in 30 days. renew now to keep...",
		time: "feb 2",
		date: "feb 2, 2026",
		unread: false,
		starred: false,
		encrypted: false,
		body: "your ENS domain h.eth is expiring soon.\n\ndomain: h.eth\nexpires: march 9, 2026\nrenewal cost: ~0.003 ETH/year\n\nrenew at app.ens.domains to avoid losing your name.",
	},
	{
		id: 15,
		folder: "trash",
		from: "noreply@scam.xyz",
		to: "hi@h.xyz",
		subject: "you won 10,000 USDT! claim now",
		preview: "congratulations! your wallet has been selected for an exclusive airdrop...",
		time: "feb 3",
		date: "feb 3, 2026",
		unread: false,
		starred: false,
		encrypted: false,
		body: "congratulations! your wallet has been selected for an exclusive airdrop of 10,000 USDT.\n\nconnect your wallet at totally-legit-site.xyz to claim.\n\n(this message was automatically flagged as suspicious)",
	},
	{
		id: 16,
		folder: "trash",
		from: "token-launch@spam.io",
		to: "hi@h.xyz",
		subject: "exclusive presale: 1000x gem",
		preview: "don't miss the next moonshot! our AI-powered defi protocol is launching...",
		time: "feb 2",
		date: "feb 2, 2026",
		unread: false,
		starred: false,
		encrypted: false,
		body: "don't miss the next moonshot! our AI-powered defi protocol is launching in 24 hours.\n\nearly investors get 50% bonus tokens.\n\n(this message was automatically flagged as spam)",
	},
]
